### ISSUE TITLE
Can't see our actions from organization repositories

### ISSUE THREAD

**Issue by DanielDornhardt** [tsimbalar/gha-build-monitor#300]
Hello there!

a) this looks and feels really great, software & technology-wise! It feels really clean! Thank you for creating & _sharing_ this!

b) Unfortunately I can't see any of our actions, do you have an Idea what could be going on? I've

  - installed Docker on my Mac (ARM version, but still, that seems to work ok)
  - Started the docker server
  - seems to be running great! (I'll add all screenshots below)
  
  - I've created my PAT / Personal Access Token
  - Ive installed & started catlight and added the 'cat-light compatible' server as per instructions.
  - I've added the token & chose auth via token.

It all looks good to me, but I can't get any actions to show? The list is empty and nothing seems to be happening when I choose "All"?

-> I'll add some screenshots of catlight & the requests/responses from the docker logs. Maybe you can give me a hint whether I'm doing something wrong?

**Additional Info**: The actions i'm looking for are in a repository of an organization i'm a member of. Maybe that's an issue? Do I have to get the token somewhere else? Is this supported?

It looks to me that the request to the github's API `/builds` is happening & successfull but it doesn't return any actions?

Thank you and best wishes
  
<img width="683" alt="image" src="https://user-images.githubusercontent.com/3845924/167801924-4c3d121d-860e-43c7-9456-c1f86476698d.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/3845924/167802943-5fea1784-3204-474e-9495-5b27f3ca388c.png">

![image](https://user-images.githubusercontent.com/3845924/167803064-22c338d2-ccf1-4f47-a440-f62e0286e181.png)

**Comment by tsimbalar** [comment]
Hi @DanielDornhardt 
Thanks a lot for the detailed report. 

I've observed something similar too, lately ... Up until some months ago, I could properly see all the workflows of all the repos of the organization I'm part of ... yet lately they no longer seem to appear ... 

I haven't had the time to look into it, but this issue might be the nudge I needed :) Will take a look

**Comment by DanielDornhardt** [comment]
Thank you, you're very welcome! We've gotta keep an eye on our pipelines, they seem to like to become red the moment we look away... 😅

**Comment by DanielDornhardt** [comment]
Hi, thank you @tsimbalar - stupid question - will you do a refresh / release of te docker image for this if this works out?

Because I actually don't know how to patch this in... I'd probably have to release my own docker image? I'm just a user in this case 😅 ...

**Comment by tsimbalar** [comment]
oops, I was not expecting to close the issue 😓  
I'll re-open, and tell you when a new release is published ... 
and then you can follow the steps in https://github.com/tsimbalar/gha-build-monitor#how-to-upgrade to upgrade :)

**Comment by DanielDornhardt** [comment]
PS: I've sent you an email, check your spam if you didn't get it.
